export interface CityData {
  slug: string;
  name: string;
  metroSlug: string;
  metroName: string;
  metaTitle: string;
  metaDesc: string;
  intro: string;
  reasons: { title: string; body: string }[];
  faqs: { q: string; a: string }[];
  neighbors: string[]; // city slugs
}

export const CITIES_DATA: CityData[] = [
  // ─── SAN ANTONIO METRO ───
  {
    slug: "san-antonio",
    name: "San Antonio",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in San Antonio, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides licensed, insured house cleaning and commercial cleaning in San Antonio, TX. 5-star rated, eco-friendly, flat-rate pricing. Get a free quote today.",
    intro: "San Antonio is one of the most vibrant cities in Texas — from the historic River Walk and King William District to the military communities surrounding Fort Sam Houston and Lackland AFB. With a city this large and this busy, keeping your home or business clean shouldn't be one more thing on your list. TQ Cleaners serves San Antonio families and businesses with the same 5-star consistency we're known for across Texas — background-checked teams, eco-friendly products, and flat-rate pricing that eliminates surprises. Whether you're in Alamo Heights, the Stone Oak corridor, the South Side, or anywhere in between, TQ Cleaners brings professional-grade cleaning directly to your door. We understand the unique pace of San Antonio life — fast-growing, family-focused, and deeply connected to its military and cultural roots.",
    reasons: [
      { title: "Same-Day Availability", body: "San Antonio's size means demand is high — we staff for it. Same-day and next-day quotes are available for most neighborhoods." },
      { title: "Large-Home Crew Capacity", body: "San Antonio homes average larger square footage than most Texas cities. We staff multi-person crews for efficient, thorough cleans on any property size." },
      { title: "Military-Family Scheduling", body: "We know military schedules don't always follow civilian patterns. We offer flexible windows, evening availability, and PCS move-out specialization for Alamo City service members." },
    ],
    faqs: [
      { q: "Do you serve all San Antonio neighborhoods?", a: "Yes — from the Medical Center and downtown to Alamo Heights, Stone Oak, the South Side, and the far northwest. If you're in the greater San Antonio area, we can reach you." },
      { q: "Can you do a last-minute deep clean before a military PCS move-out?", a: "Absolutely. Military move-outs are one of our most common requests in San Antonio. We specialize in tight-timeline cleans that meet landlord inspection standards and include a deposit-back guarantee." },
    ],
    neighbors: ["alamo-heights", "helotes", "leon-valley", "schertz"],
  },
  {
    slug: "alamo-heights",
    name: "Alamo Heights",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Alamo Heights, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides trusted house cleaning in Alamo Heights, TX — heritage home expertise, discreet service, flat-rate pricing. Licensed and insured. Get a free quote.",
    intro: "Alamo Heights is one of San Antonio's most distinguished neighborhoods — a tight-knit, established enclave entirely surrounded by Loop 410 with a character all its own. Older homes, mature trees, and a strong sense of community define Alamo Heights, and the residents here expect a level of care and discretion that matches their neighborhood's reputation. TQ Cleaners has developed real expertise cleaning Alamo Heights' mix of heritage homes and updated interiors — understanding older finishes, wood floors, original fixtures, and the care required to clean them without damage. We're trusted by Alamo Heights families who want the same reliable face at their door every visit, not a rotating cast of strangers. If you live on Broadway, Nacogdoches, or anywhere within the Heights, TQ Cleaners is ready to be your long-term cleaning partner.",
    reasons: [
      { title: "Heritage-Home Expertise", body: "Older homes require gentler, surface-specific care. Our team is trained on wood floors, original tile, and vintage finishes common throughout Alamo Heights." },
      { title: "Discreet, Consistent Service", body: "The same vetted team every visit. No strangers, no surprises — exactly the kind of reliable, quiet service Alamo Heights residents expect." },
      { title: "Morning Windows Available", body: "We prioritize AM scheduling for Alamo Heights clients who prefer the team in and out before the day gets busy." },
    ],
    faqs: [
      { q: "Do you have experience with older homes and original hardwood floors?", a: "Yes — Alamo Heights is one of our most common service areas for heritage homes. We use pH-appropriate, wood-safe products and train our teams on surface-specific care for original flooring, plaster walls, and vintage tile." },
      { q: "Can I have the same team every visit?", a: "Yes, and we prioritize this for Alamo Heights clients. Consistent team assignment is a cornerstone of how TQ Cleaners operates — your team learns your preferences, your home, and your standards." },
    ],
    neighbors: ["san-antonio", "leon-valley", "stone-oak", "the-dominion"],
  },
  {
    slug: "helotes",
    name: "Helotes",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Helotes, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers professional house cleaning in Helotes, TX — large home experience, pet-friendly products, Saturday availability. Licensed and insured. Free quote today.",
    intro: "Helotes sits at the western edge of San Antonio where the city gives way to the Texas Hill Country — larger lots, newer builds, and a suburban lifestyle with real space to breathe. Homes in Helotes tend to run larger than the city average, with open floor plans, sprawling square footage, and the kind of busy family energy that makes professional cleaning not a luxury but a necessity. TQ Cleaners regularly services Helotes homes with multi-person crews built for larger properties — getting in, executing the full checklist efficiently, and getting out without disrupting your day. We're pet-friendly, eco-conscious, and experienced with the newer construction finishes common throughout Helotes developments like Sonoma Ranch and I-10 corridor neighborhoods.",
    reasons: [
      { title: "Large-Square-Foot Experience", body: "Helotes homes run big. We staff appropriately-sized crews so your clean is thorough and efficient — never rushed, never dragging." },
      { title: "Pet-Friendly Products", body: "Plant-based, non-toxic cleaning products safe for dogs, cats, and kids. No harsh fumes in the home your pets live in." },
      { title: "Saturday Availability", body: "Helotes families are busy during the week. We keep Saturday slots available and don't charge a premium for weekend service." },
    ],
    faqs: [
      { q: "Can you clean homes over 3,000 square feet in Helotes?", a: "Absolutely — larger homes are our specialty in Helotes. We quote based on square footage and scope, not hourly rate, so you know the exact cost upfront. We staff 3–4 person crews for larger properties." },
      { q: "Are your products safe for pets and small children?", a: "Yes — all TQ Cleaners products are plant-based, EPA Safer Choice certified, and free from harsh chemicals. No bleach fumes, no ammonia, no synthetic fragrance. Safe for pets and children to return to immediately after cleaning." },
    ],
    neighbors: ["san-antonio", "leon-valley", "boerne", "the-dominion"],
  },
  {
    slug: "leon-valley",
    name: "Leon Valley",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Leon Valley, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides affordable house and apartment cleaning in Leon Valley, TX. Fast standard cleans, eco-friendly products, flat-rate pricing. Licensed and insured.",
    intro: "Leon Valley is one of San Antonio's most established inner-ring suburbs — a compact, practical community on the northwest side with a mix of single-family homes and apartment complexes that reflect the real texture of San Antonio's workforce. Life in Leon Valley moves fast, and TQ Cleaners is built to match that pace. We specialize in efficient standard cleans for busy households, apartment unit turnovers for property managers, and recurring maintenance plans that keep homes consistently clean without eating into limited time or budget. Our flat-rate pricing means Leon Valley clients always know exactly what they're paying — no hourly ambiguity, no surprise charges when a bathroom took longer than expected. Eco-friendly products, consistent teams, and reliable scheduling make TQ Cleaners the cleaning company of choice in Leon Valley.",
    reasons: [
      { title: "Apartment-Turn Experts", body: "Leon Valley has a strong rental market. We handle efficient apartment turnovers for property managers and tenants preparing for deposit inspection." },
      { title: "Fast Standard Cleans", body: "Efficient, focused service for busy households. We execute the full checklist thoroughly without unnecessary upsells or time padding." },
      { title: "Eco-Friendly Products", body: "Non-toxic, kid- and pet-safe products throughout. Better for your family and better for Leon Valley's air quality indoors." },
    ],
    faqs: [
      { q: "Do you offer move-out cleaning for apartment rentals in Leon Valley?", a: "Yes — move-out cleaning is one of our most-requested services in Leon Valley. We clean to deposit-return standard with a guarantee: if the landlord cites a cleaning issue, we return within 48 hours at no charge." },
      { q: "How quickly can you schedule a first clean?", a: "Most Leon Valley clients can be scheduled within 2–3 business days. For urgent move-outs or deep cleans, call us directly — we maintain same-week capacity for new clients." },
    ],
    neighbors: ["san-antonio", "helotes", "alamo-heights", "converse"],
  },
  {
    slug: "converse",
    name: "Converse",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Converse, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners specializes in PCS move-out cleaning in Converse, TX near Randolph AFB. Deposit-back guarantee, flexible scheduling, licensed and insured. Free quote.",
    intro: "Converse sits in the northeast corner of the San Antonio metro, just minutes from Randolph Air Force Base — which means Converse sees more PCS moves, military family transitions, and rental turnovers than almost anywhere else in the region. TQ Cleaners has built real expertise around the unique demands of military household cleaning: tight move-out timelines, landlord-inspection-standard cleans, and the deposit-back pressure that comes with government-standard housing requirements. Whether you're a service member facing a 30-day PCS deadline, a landlord preparing a property for the next military tenant, or a Converse family that simply needs consistent residential cleaning, TQ Cleaners shows up on time, cleans to standard, and stands behind every job with our satisfaction guarantee.",
    reasons: [
      { title: "PCS Move-Out Specialists", body: "We understand the strict timelines and cleaning standards required for military PCS moves — and we've helped hundreds of service members get their full deposit back." },
      { title: "Flexible Timing", body: "Military schedules don't fit 9–5 windows. We offer evening and weekend availability to accommodate deployment schedules and last-minute PCS notices." },
      { title: "Deposit-Back Guarantee", body: "If a landlord cites a cleaning issue after our clean, we return within 48 hours to correct it at no charge. Your deposit is protected." },
    ],
    faqs: [
      { q: "Can you do emergency same-week PCS move-out cleans in Converse?", a: "Yes — we maintain priority scheduling capacity for Converse and Randolph AFB area move-outs. Call us directly at (956) 306-6378 for urgent timelines." },
      { q: "Do you clean base housing in addition to off-base rentals?", a: "We clean off-base rental properties in and around Converse. For on-base housing, regulations vary — contact your housing office for their approved vendor process, and we can often be added." },
    ],
    neighbors: ["san-antonio", "universal-city", "schertz", "leon-valley"],
  },
  {
    slug: "universal-city",
    name: "Universal City",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Universal City, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides PCS move-in/move-out cleaning in Universal City, TX near Randolph AFB. Insured, bonded, evening availability. Get a free quote today.",
    intro: "Universal City is a tight-knit community built around Randolph Air Force Base — a place where neighbors know each other, military families rotate in and out on predictable PCS cycles, and trust in a service provider matters as much as the price. TQ Cleaners has earned that trust in Universal City by delivering consistent, inspection-grade cleaning for move-ins, move-outs, and ongoing residential service. We're fully insured and bonded — something landlords and property managers in the Randolph corridor specifically request. Our evening availability accommodates service members who can't be home during standard business hours, and our PCS move-in and move-out cleans are specifically designed to meet the standards military housing inspectors expect.",
    reasons: [
      { title: "PCS Move-In / Move-Out Ready", body: "Inspection-grade cleans built around military housing standards — move in clean, move out deposit-ready." },
      { title: "Insured & Bonded", body: "Full liability insurance and bonding documentation available for landlords, property managers, and base housing offices that require it." },
      { title: "Evening Availability", body: "We don't close at 5 PM. Evening cleaning windows accommodate military members who can't be home during the day." },
    ],
    faqs: [
      { q: "How quickly can you turn around a PCS move-out clean in Universal City?", a: "We typically accommodate Universal City move-out cleans within 24–48 hours. For truly urgent needs, call us and we'll exhaust every scheduling option." },
      { q: "Can you provide documentation for base housing or property managers?", a: "Yes — we provide a service invoice, our insurance certificate, and a written confirmation of what was cleaned. Most Universal City landlords and property managers accept our standard documentation." },
    ],
    neighbors: ["converse", "san-antonio", "schertz", "new-braunfels"],
  },
  {
    slug: "schertz",
    name: "Schertz",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Schertz, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers house cleaning in Schertz, TX — post-construction cleans, recurring family service, easy online booking. Licensed and insured. Get a free quote.",
    intro: "Schertz is one of the fastest-growing communities in the San Antonio metro — a corridor suburb along I-35 where new subdivisions seem to pop up overnight and young families are putting down roots at a rapid pace. New construction is everywhere in Schertz, which means post-build construction cleans are one of the most common requests we receive from the area. TQ Cleaners handles post-construction debris, drywall dust, and builder-grade residue with the specialized products and techniques that new builds require. Beyond new construction, Schertz families rely on TQ Cleaners for recurring weekly and bi-weekly maintenance — consistent, reliable cleaning that keeps pace with active household life in this growing community. Easy online booking and transparent flat-rate pricing make it simple to get started.",
    reasons: [
      { title: "Post-Build Construction Cleans", body: "New construction requires specialized cleaning — drywall dust, construction adhesive, paint residue. We handle it properly without damaging new finishes." },
      { title: "Recurring Family Service", body: "Schertz is a young-family community. Our recurring plans keep busy households consistently clean on a schedule that works around school, sports, and work." },
      { title: "Easy Online Booking", body: "Get a quote and schedule your first clean without playing phone tag. Flat-rate pricing, clear scheduling, no surprises." },
    ],
    faqs: [
      { q: "Do you offer post-construction cleaning for new builds in Schertz?", a: "Yes — post-construction cleaning is one of our most-requested services in Schertz. We clean builders' debris, drywall dust, sticker residue, and construction grime using techniques that protect new surfaces and finishes." },
      { q: "How do I start a recurring service in Schertz?", a: "Call or fill out our quote form online. We'll discuss your home size, frequency preference, and any specific needs, then give you a flat-rate quote. Most new Schertz clients are scheduled within a week." },
    ],
    neighbors: ["san-antonio", "converse", "universal-city", "new-braunfels"],
  },
  {
    slug: "new-braunfels",
    name: "New Braunfels",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in New Braunfels, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides STR Airbnb and house cleaning in New Braunfels, TX. High-volume turnover specialists for Guadalupe and Comal tubing season. Free quote today.",
    intro: "New Braunfels is one of Texas's most beloved river towns — a historic community where the Guadalupe and Comal rivers draw millions of tubers, kayakers, and vacationers every summer season. That tourism economy has made New Braunfels one of the densest short-term rental markets in the state, with Airbnb and VRBO properties lining the river corridors and filling up from Memorial Day through Labor Day. TQ Cleaners has built specialized capacity for the New Braunfels STR market: high-volume same-day turnovers, linen handling, restocking, and the kind of hotel-quality resets that earn 5-star reviews and keep properties booked. Beyond the STR market, New Braunfels families — both longtime residents and the many young families relocating to this growing community — rely on TQ Cleaners for consistent, professional residential cleaning year-round.",
    reasons: [
      { title: "High-Volume STR Turnovers", body: "Tubing season brings back-to-back bookings. We handle multiple same-day turnovers and are built for the pace of peak New Braunfels tourism season." },
      { title: "Tourist-Season Flexibility", body: "Summer weekends are peak demand in New Braunfels. We staff for it and keep STR hosts covered through the busiest weeks." },
      { title: "Weekly Family Service", body: "Beyond the STR market, New Braunfels families count on TQ for consistent, professional residential cleaning year-round." },
    ],
    faqs: [
      { q: "Can you handle multiple STR turnovers on the same day in New Braunfels?", a: "Yes — we schedule STR turnovers in clusters and staff the appropriate crew size for back-to-back properties. Peak season availability books fast; contact us in early spring to lock in your summer schedule." },
      { q: "Do you service vacation rentals on the Guadalupe and Comal river corridors?", a: "Yes — the river-access STR properties along Gruene and the Highway 46 corridor are among our most-cleaned properties in New Braunfels. We know the terrain, the access, and the typical scope of these properties." },
    ],
    neighbors: ["san-antonio", "schertz", "universal-city", "boerne"],
  },
  {
    slug: "boerne",
    name: "Boerne",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Boerne, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides ranch and luxury home cleaning in Boerne, TX. Well-water-safe eco products, large property flat rates. Licensed and insured. Free quote today.",
    intro: "Boerne is the jewel of the Texas Hill Country west of San Antonio — a historic town of limestone buildings, cypress-lined Cibolo Creek, and some of the most beautiful residential properties in South Texas. Upscale homes, working ranches, and sprawling Hill Country estates define Boerne's character, and they demand a cleaning service that can match that level. TQ Cleaners has developed specific expertise for Boerne's property mix: large-footage homes requiring multi-person crews, ranch properties with unique cleaning challenges, well-water-safe products that won't harm irrigation systems or filtration, and the care required for high-end surfaces, custom tile, and luxury finishes. Boerne homeowners trust TQ Cleaners because we treat every property with the same respect and attention to detail that the community itself embodies.",
    reasons: [
      { title: "Ranch & Large-Property Care", body: "From Hill Country estates to working ranches, we staff appropriately for properties of any size and complexity in the Boerne area." },
      { title: "Well-Water-Safe Eco Products", body: "Our plant-based, biodegradable products are safe for well-water systems, septic systems, and the sensitive Hill Country ecosystem." },
      { title: "Large-Property Flat Rates", body: "Even 5,000+ sq ft properties get a single flat-rate quote. No hourly billing, no scope creep — just a clean you can budget for confidently." },
    ],
    faqs: [
      { q: "Do your products work safely with well-water and septic systems common in Boerne?", a: "Yes — all TQ Cleaners products are biodegradable, phosphate-free, and safe for septic systems. We specifically use eco products that won't disrupt the beneficial bacteria in septic tanks or harm well-water quality when rinsed." },
      { q: "Can you clean large ranch homes and guest houses in the Boerne area?", a: "Absolutely. Multi-structure and guest-house properties are common in the Boerne area. We quote each structure separately and build a coordinated cleaning plan across the whole property." },
    ],
    neighbors: ["san-antonio", "helotes", "new-braunfels", "stone-oak"],
  },
  {
    slug: "stone-oak",
    name: "Stone Oak",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in Stone Oak, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides luxury house cleaning in Stone Oak, San Antonio, TX. Discreet service, gated-community experience, weekly maintenance plans. Free quote today.",
    intro: "Stone Oak is San Antonio's premier master-planned enclave on the far north side — an affluent, gated-community-heavy corridor where luxury homes, professional families, and high expectations define the landscape. TQ Cleaners has built a reputation in Stone Oak for delivering exactly the kind of discreet, consistent, detail-oriented service that residents in this community expect. We don't rotate random teams through your home. We assign dedicated, vetted cleaning professionals who learn your property, respect your privacy, and maintain the same 5-star standard every visit. Stone Oak homeowners trust TQ Cleaners for weekly luxury maintenance plans, quarterly deep cleans, and the kind of relationship-based service that turns a cleaning company into a long-term household partner.",
    reasons: [
      { title: "Luxury Weekly Maintenance", body: "Premium recurring service for Stone Oak's high-standard homes — same checklist, same team, same spotless result every single visit." },
      { title: "Discretion & Privacy", body: "Your home is your private space. We operate quietly, respectfully, and never share client information or schedule details." },
      { title: "Gated-Community Experience", body: "We're familiar with Stone Oak's gated communities and HOA access requirements. Scheduling access is seamless." },
    ],
    faqs: [
      { q: "Can you accommodate the access requirements for Stone Oak's gated communities?", a: "Yes — we're familiar with Stone Oak HOA and gated-community access processes. We work with you to establish the right access method (gate codes, guard registration, lockbox) before the first visit so every subsequent clean is seamless." },
      { q: "Do you offer luxury weekly maintenance plans in Stone Oak?", a: "Yes — premium weekly recurring service is one of our most popular offerings in Stone Oak. Includes dedicated team assignment, consistent scheduling, and access to quarterly deep-clean add-ons at a bundled rate." },
    ],
    neighbors: ["san-antonio", "alamo-heights", "the-dominion", "boerne"],
  },
  {
    slug: "the-dominion",
    name: "The Dominion",
    metroSlug: "san-antonio-metro",
    metroName: "San Antonio Metro",
    metaTitle: "House Cleaning in The Dominion, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides estate-level cleaning in The Dominion, San Antonio. Vetted teams, concierge communication, luxury detail. Licensed and insured. Free quote.",
    intro: "The Dominion is San Antonio's most prestigious address — a private, guarded community in the far northwest where estates, executive homes, and luxury properties represent the pinnacle of residential living in South Texas. Cleaning at this level is not simply about showing up with supplies. It requires vetted teams who've been background-checked and reference-verified, a process that takes longer but produces the trust that Dominion residents require. It requires concierge-level communication — proactive updates, confirmed arrival windows, detailed post-clean summaries, and immediate escalation if anything is ever less than perfect. TQ Cleaners built our estate-level service program specifically for communities like The Dominion, where the standard isn't just clean — it's flawless. Every visit is treated as an opportunity to earn the next one.",
    reasons: [
      { title: "Estate-Level Detail", body: "50-point checklist executed with the precision and care that estate properties demand — no shortcuts, no overlooked corners, no excuses." },
      { title: "Rigorously Vetted Teams", body: "Every cleaner assigned to Dominion properties has passed background checks, reference verification, and in-home training evaluations before their first visit." },
      { title: "Concierge Communication", body: "Proactive scheduling confirmations, arrival notifications, completion summaries, and immediate response to any feedback or concern." },
    ],
    faqs: [
      { q: "How do you handle access and security for The Dominion properties?", a: "We register every team member with The Dominion's guard-controlled entry before their first visit. Access procedures are documented, followed precisely, and updated immediately if your household access changes." },
      { q: "What if I am dissatisfied with any aspect of an estate clean?", a: "We return within 24 hours at no charge and make it right — no questions asked, no minimizing your concern. Estate-level service means estate-level accountability. Luis personally reviews any feedback from Dominion clients." },
    ],
    neighbors: ["san-antonio", "stone-oak", "helotes", "boerne"],
  },
  // ─── AUSTIN METRO ───
  {
    slug: "austin",
    name: "Austin",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Austin, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides 5-star house cleaning in Austin, TX — same-day quotes, tech-schedule flexibility, allergy-sensitive eco products. Licensed and insured. Free quote.",
    intro: "Austin is the beating heart of Texas's tech economy — a city that never stops moving, from the downtown skyline to the Westlake hills to the sprawling suburbs along every corridor. Austin homeowners are busy, highly connected, and have high standards for every service they bring into their home. TQ Cleaners is built for Austin: fast same-day quotes through our online form, flexible scheduling that adapts to tech industry hours and remote-work schedules, and allergy-sensitive eco products that address Austin's notorious cedar, oak, and mold allergen load. Whether you're in Travis Heights, South Congress, Mueller, Tarrytown, or the Domain corridor, TQ Cleaners brings consistent, professional cleaning to your door — so you can spend your time on the work and life that brought you to Austin in the first place.",
    reasons: [
      { title: "Same-Day Quotes", body: "Austin runs fast. Get a flat-rate quote in under 60 seconds through our form or a 10-minute call — no waiting days for an estimate." },
      { title: "Tech-Schedule Flexibility", body: "We accommodate WFH schedules, flexible start times, and the non-standard hours that define Austin's tech and creative workforce." },
      { title: "Allergy-Sensitive Eco Products", body: "Cedar fever, oak pollen, and Austin's moisture levels create real indoor allergen challenges. Our HEPA-equipped vacuums and fragrance-free products help." },
    ],
    faqs: [
      { q: "Do you clean condos and downtown Austin high-rises?", a: "Yes — we clean condos, townhomes, apartments, and single-family homes throughout Austin. For high-rise properties, we coordinate with building management on access and elevator scheduling." },
      { q: "I work from home in Austin — can you clean around my schedule?", a: "Absolutely. We accommodate WFH schedules, specific room-sequencing requests, and quiet operation near home offices. Just tell us your needs when booking." },
    ],
    neighbors: ["round-rock", "cedar-park", "pflugerville", "lakeway"],
  },
  {
    slug: "round-rock",
    name: "Round Rock",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Round Rock, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides move-in cleaning and recurring house cleaning in Round Rock, TX. Relocation specialists, weekend availability. Licensed and insured. Free quote.",
    intro: "Round Rock has become one of the most desirable suburbs in the Austin metro — a community that combines excellent schools, the Dell campus, and easy access to Austin's job market with the space and affordability that the city itself can no longer offer. Thousands of families relocate to Round Rock every year from California, the Pacific Northwest, and the Northeast, arriving in a new home in a new city and needing everything set up — including professional cleaning — before they can truly settle in. TQ Cleaners specializes in relocation move-in cleans that give Round Rock newcomers a genuinely fresh start in their new home. Beyond relocations, Round Rock families count on TQ Cleaners for reliable recurring service that keeps pace with the active, school-and-sports household life that defines this community.",
    reasons: [
      { title: "Relocation Move-In Experts", body: "We specialize in getting newly purchased and rented homes spotless before the furniture arrives — perfect for Round Rock's constant relocation influx." },
      { title: "Recurring Family Service", body: "Round Rock family life is active. Our bi-weekly and weekly plans keep households consistently clean through the school year and summer." },
      { title: "Weekend Availability", body: "Move-ins happen on weekends. Deep cleans happen on weekends. We staff for it and don't charge a weekend premium." },
    ],
    faqs: [
      { q: "We're relocating to Round Rock from out of state — can you clean the house before we arrive?", a: "Yes — this is one of our most common requests in Round Rock. We coordinate access with your realtor, property manager, or a trusted local contact and have the home move-in ready before you arrive. We'll send photo confirmation when the clean is complete." },
      { q: "Do you offer recurring service for large families in Round Rock?", a: "Absolutely. Our weekly and bi-weekly plans are built for active family households. We assign the same team every visit so they know your home and your preferences from day one." },
    ],
    neighbors: ["austin", "pflugerville", "cedar-park", "georgetown"],
  },
  {
    slug: "pflugerville",
    name: "Pflugerville",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Pflugerville, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers post-build and recurring house cleaning in Pflugerville, TX. Busy-family weekly service, flat-rate pricing. Licensed and insured. Free quote today.",
    intro: "Pflugerville is northeast Austin's fastest-growing suburb — a community that has expanded dramatically over the past decade as new subdivisions, retail corridors, and families priced out of Austin proper have poured in. New construction is a defining feature of Pflugerville's landscape, and post-build construction cleans are among our most frequent service calls in the area. Builder-grade residue, drywall dust, adhesive streaks, and the countless small messes that new construction leaves behind require specialized technique and the right products to remove without damaging brand-new surfaces. TQ Cleaners handles post-construction Pflugerville cleans with precision, and transitions seamlessly into recurring family service for new homeowners who've just moved in and want to start fresh.",
    reasons: [
      { title: "Post-Build Construction Cleans", body: "Pflugerville's boom means new builds everywhere. We specialize in construction cleanup that prepares new homes for move-in day." },
      { title: "Busy-Family Weekly Service", body: "Young families in Pflugerville need consistent, reliable cleaning. Our weekly and bi-weekly plans are built for high-traffic households." },
      { title: "Flat-Rate Pricing", body: "Know the price before we show up. No hourly tracking, no per-room add-ons — one flat rate that covers the agreed scope every time." },
    ],
    faqs: [
      { q: "How soon after construction is complete can you do a post-build clean in Pflugerville?", a: "We recommend scheduling the post-build clean for the day construction clears — before furniture delivery. We can typically accommodate 24–48 hours notice for Pflugerville post-build cleans." },
      { q: "What's included in a post-construction clean vs. a standard deep clean?", a: "Post-construction includes everything in a deep clean plus: removing paint overspray, adhesive labels from fixtures and appliances, drywall dust from all surfaces and vents, construction debris, and final inspection prep. It's a different scope that requires different products and techniques." },
    ],
    neighbors: ["austin", "round-rock", "cedar-park", "kyle"],
  },
  {
    slug: "cedar-park",
    name: "Cedar Park",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Cedar Park, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers family-friendly house cleaning in Cedar Park, TX. Pet-safe products, flexible scheduling, easy cancellation. Licensed and insured. Free quote.",
    intro: "Cedar Park is one of the northwest Austin corridor's most family-friendly communities — a place where young professionals, tech workers, and growing families have planted roots within reach of Austin's job market and surrounded by excellent schools and amenities. The Cedar Park household tends to be active, busy, and full of kids and pets — exactly the kind of home where consistent professional cleaning makes the biggest difference in quality of life. TQ Cleaners serves Cedar Park with family-first service: pet-safe, non-toxic products that are genuinely safe for the dogs, cats, and toddlers in your home; flexible scheduling that accommodates school drop-off windows and WFH hours; and easy cancellation policy that respects the reality of family life's unpredictability.",
    reasons: [
      { title: "Family-Friendly Scheduling", body: "Morning windows, afternoon blocks, weekend slots — we schedule around school and work, not the other way around." },
      { title: "Pet-Safe Products", body: "100% non-toxic, pet-safe products throughout. No essential oil diffusers (toxic to cats), no harsh fumes — just clean that's safe for every family member." },
      { title: "Flexible Cancellation", body: "Life with kids is unpredictable. We offer easy reschedule and cancellation options — just give us 24 hours notice and there's no fee." },
    ],
    faqs: [
      { q: "Are your cleaning products genuinely safe for pets and young children in Cedar Park?", a: "Yes — we use EPA Safer Choice certified, plant-based products with no synthetic fragrance, no chlorine bleach, and no ammonia. Safe for pets and children to be around immediately after cleaning. We also avoid essential oils, which can be toxic to cats." },
      { q: "How flexible is your scheduling for Cedar Park families?", a: "Very flexible. We offer morning, midday, and afternoon windows on weekdays, and Saturday slots. We'll work with your household's specific schedule constraints." },
    ],
    neighbors: ["austin", "round-rock", "leander", "pflugerville"],
  },
  {
    slug: "kyle",
    name: "Kyle",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Kyle, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers affordable house cleaning in Kyle, TX. New-build cleans, standard recurring plans, same-week start. Licensed and insured. Free quote today.",
    intro: "Kyle has exploded in growth over the past five years — one of the fastest-growing cities in the entire country, drawing families south of Austin with affordable home prices, good schools, and the promise of Hill Country proximity without Hill Country prices. New construction is the dominant story in Kyle, with subdivisions like Plum Creek, Waterleaf, and Anthem filling in rapidly. TQ Cleaners handles new-build construction cleans throughout Kyle, getting homes move-in ready for families arriving from Austin, the coasts, and across the country. For established Kyle residents, our standard recurring plans deliver consistent cleaning at pricing that makes sense for this community — affordable, flat-rate, and reliable. Same-week scheduling gets new clients started quickly without a long waiting list.",
    reasons: [
      { title: "New-Build Construction Cleans", body: "Kyle's growth is driven by new construction. We specialize in post-build cleans that get brand-new homes ready for move-in day." },
      { title: "Affordable Standard Plans", body: "Kyle homeowners get the same quality TQ Cleaners service at flat-rate pricing designed for this market — no Austin premium." },
      { title: "Same-Week Start", body: "New clients in Kyle are typically scheduled within the same week of inquiry. No long waitlists, fast service." },
    ],
    faqs: [
      { q: "Do you service the newer subdivisions in Kyle like Plum Creek and Anthem?", a: "Yes — we clean throughout Kyle including all major subdivisions. New builds in these communities are among our most common Kyle service calls." },
      { q: "Is pricing the same as Austin, or do you have more affordable rates for Kyle?", a: "Our flat-rate pricing is based on home size and scope, not location. Kyle homeowners receive the same transparent pricing as Austin clients — no geographic premium." },
    ],
    neighbors: ["austin", "buda", "pflugerville", "leander"],
  },
  {
    slug: "buda",
    name: "Buda",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Buda, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides locally owned house cleaning in Buda, TX. Community-rooted team, transparent pricing, reliable service. Licensed and insured. Free quote.",
    intro: "Buda may be one of the smaller communities in the Austin metro, but it has one of the strongest senses of local identity — a small-town character that residents fiercely protect even as growth presses in from Kyle and Austin to the north. For Buda residents, local ownership matters. Trust matters. Knowing who's in your home and why they're there matters. TQ Cleaners is owner-operated by Luis, who built this company on the same values that Buda residents live by: accountability, consistency, and doing the job right the first time. When you book TQ Cleaners in Buda, you're supporting a local business that treats your home with the same care you do — not a franchise that ships random crews to meet a quota.",
    reasons: [
      { title: "Local-Owner Accountability", body: "Owner-operated means Luis personally stands behind every clean in Buda. You have a real person to call, not a call center." },
      { title: "Community-Rooted Team", body: "Our team serves the greater Austin and San Antonio metros as neighbors — not as a distant corporate service." },
      { title: "Transparent Pricing", body: "One flat rate quoted before we arrive. Every time. No hourly billing, no surprise charges, no upsells at the door." },
    ],
    faqs: [
      { q: "Is TQ Cleaners a local business or a franchise?", a: "TQ Cleaners is locally owned and operated by Luis — not a franchise with corporate standards imposed from outside Texas. Every decision, every hire, and every client relationship is managed locally." },
      { q: "Do you service the newer Buda subdivisions off Windy Hill?", a: "Yes — we clean throughout Buda including the newer residential developments along FM 967 and Windy Hill Road corridors." },
    ],
    neighbors: ["kyle", "austin", "dripping-springs", "leander"],
  },
  {
    slug: "leander",
    name: "Leander",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Leander, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides house cleaning in Leander, TX — new-construction expertise, Hill Country reach, reliable weekly service. Licensed and insured. Free quote.",
    intro: "Leander is one of the northwest Austin corridor's most dynamic growth communities — rapidly expanding westward into the Texas Hill Country with master-planned developments like Crystal Falls, Bar W Ranch, and Bluffview filling in along Highway 183A. The Leander MetroRail station has made this community a genuine Austin commuter hub, drawing young professionals and families who want space without the Austin premium. New construction is constant in Leander, and TQ Cleaners handles post-build cleans throughout the newest developments, getting homes move-in ready for families arriving from within Texas and across the country. Our weekly and bi-weekly recurring service keeps Leander's busy commuter households consistently clean, and our Hill Country reach means we can also service properties west of Leander toward Liberty Hill and beyond.",
    reasons: [
      { title: "New-Construction Expertise", body: "Leander's rapid growth means constant new builds. We specialize in post-construction cleans that prepare homes for move-in." },
      { title: "Hill Country Reach", body: "We service Leander and properties west toward Liberty Hill and the Hill Country edge — areas many Austin cleaning companies won't reach." },
      { title: "Reliable Weekly Service", body: "Leander's commuter families need consistent, on-time cleaning. We deliver the same result every visit without excuses or rescheduling." },
    ],
    faqs: [
      { q: "Do you service the newer developments in Leander like Crystal Falls and Bar W Ranch?", a: "Yes — these are some of our most frequently serviced Leander communities. New construction in both developments generates significant post-build cleaning demand and recurring family service." },
      { q: "Can you reach properties further west of Leander toward Liberty Hill?", a: "We service Leander and the immediate surrounding area. For properties further toward Liberty Hill, call us — we'll let you know if we can accommodate based on our current coverage map." },
    ],
    neighbors: ["cedar-park", "austin", "round-rock", "georgetown"],
  },
  {
    slug: "georgetown",
    name: "Georgetown",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Georgetown, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides house cleaning in Georgetown, TX. Gentle eco products for retirees, historic-home care, flexible scheduling. Licensed and insured. Free quote.",
    intro: "Georgetown is one of Texas's most charming cities — a beautifully preserved Victorian-era downtown square surrounded by one of the most diverse residential communities in the Austin metro. Georgetown is home to Sun City Texas, one of the largest active adult communities in the country, alongside younger families drawn by the historic character, Southwestern University, and lower prices relative to Austin. TQ Cleaners serves both Georgetown demographics with tailored service: gentle eco products and flexible, retiree-friendly scheduling for Sun City residents, and thorough historic-home expertise for downtown Georgetown's heritage properties. Whatever brings you to Georgetown, TQ Cleaners brings the same professional, reliable, flat-rate cleaning that has made us trusted across the Austin metro.",
    reasons: [
      { title: "Gentle Eco Products", body: "Non-toxic, fragrance-free products safe for seniors with chemical sensitivities and perfect for Georgetown's retiree community." },
      { title: "Retiree-Friendly Scheduling", body: "Morning windows, predictable scheduling, and a consistent team that Sun City residents can plan around and trust." },
      { title: "Historic-Home Care", body: "Georgetown's downtown neighborhood features original hardwood floors, plaster walls, and period fixtures that require surface-specific, careful cleaning." },
    ],
    faqs: [
      { q: "Do you service Sun City Texas in Georgetown?", a: "Yes — we clean throughout the Sun City Texas community. We're familiar with the community's access procedures and have many regular Sun City clients. We offer senior-friendly scheduling with morning-priority windows." },
      { q: "Can you clean historic homes near the Georgetown courthouse square?", a: "Yes — we have experience with Georgetown's historic downtown residential properties, including hardwood floor care, plaster wall cleaning, and period-appropriate product selection." },
    ],
    neighbors: ["leander", "round-rock", "austin", "cedar-park"],
  },
  {
    slug: "lakeway",
    name: "Lakeway",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Lakeway, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides luxury home and Airbnb cleaning in Lakeway, TX on Lake Travis. Gated-community experience, STR turnovers. Licensed and insured. Free quote.",
    intro: "Lakeway is Austin's premier lakeside luxury community — perched above Lake Travis with estate homes, championship golf courses, and some of the most beautiful residential properties in Central Texas. It's also a thriving short-term rental market, with lake-access properties earning premium nightly rates from Austin-area visitors and destination travelers year-round. TQ Cleaners serves Lakeway's dual residential and STR market with the precision and professionalism this community demands. Luxury homes require estate-level cleaning: detail-oriented teams who treat every surface with care, consistent assignments so the same trusted faces return every visit, and the gated-community access experience that keeps things smooth. STR properties on the lake demand hotel-quality turnovers — perfect bed staging, spotless bathrooms, and photo-ready resets between every guest.",
    reasons: [
      { title: "Luxury-Home Expertise", body: "Estate-level detail for Lakeway's high-end properties — the right products for custom tile, high-end appliances, and luxury finishes." },
      { title: "Lake-Rental STR Turnovers", body: "Hotel-quality resets for Lakeway's Lake Travis STR market — same-day turnovers, linen handling, and damage photo reports." },
      { title: "Gated-Community Experience", body: "Seamless access coordination for Lakeway's gated communities — we register teams properly and maintain access documentation." },
    ],
    faqs: [
      { q: "Do you handle Lake Travis Airbnb turnovers in Lakeway?", a: "Yes — lake-access STR turnovers are one of our most popular services in Lakeway. We handle same-day check-out to check-in turnarounds and are experienced with the typical scope of Lake Travis vacation rental properties." },
      { q: "Can you service estate properties in The Hills at Lakeway or other gated sections?", a: "Yes — we're experienced with Lakeway's gated communities including The Hills and Serene Hills. We register with guard-controlled entry in advance to keep your cleaning visits seamless." },
    ],
    neighbors: ["austin", "bee-cave", "dripping-springs", "cedar-park"],
  },
  {
    slug: "bee-cave",
    name: "Bee Cave",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Bee Cave, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers luxury house cleaning in Bee Cave, TX. Detailed service, weekday windows, referral discounts. Licensed and insured. Get a free quote today.",
    intro: "Bee Cave sits at the nexus of Hill Country luxury and Austin proximity — a small incorporated city near the Shops at the Galleria that punches well above its modest square mileage in terms of residential prestige. Homes in Bee Cave tend to be large, meticulously maintained, and in neighborhoods where neighbors notice when a property isn't kept up. TQ Cleaners serves Bee Cave homeowners who expect the same from their cleaning service as they expect from every other premium service they use: detail, consistency, and a team that doesn't need to be supervised. Weekday cleaning windows fit the schedules of Bee Cave's professional and semi-retired residents, and our referral discount program makes it easy to share TQ Cleaners with neighbors and friends.",
    reasons: [
      { title: "Detailed Luxury Service", body: "Bee Cave homes are maintained at a high standard. Our team delivers the detail-oriented, surface-appropriate cleaning that premium properties require." },
      { title: "Weekday Windows Available", body: "Priority weekday scheduling for Bee Cave's professional residents — morning and midday slots to fit your schedule." },
      { title: "Referral Discounts", body: "Bee Cave is a tight-knit community. Refer a neighbor and receive a discount on your next clean — both of you benefit." },
    ],
    faqs: [
      { q: "Do you clean large homes in the Spanish Oaks or Falconhead communities in Bee Cave?", a: "Yes — Spanish Oaks and Falconhead are among our Bee Cave service areas. We're familiar with the scale and standard of homes in these communities and staff accordingly." },
      { q: "How does your referral discount program work?", a: "When a Bee Cave neighbor you referred books their first clean, you receive a credit toward your next service. There's no cap — refer as many neighbors as you like." },
    ],
    neighbors: ["lakeway", "austin", "dripping-springs", "cedar-park"],
  },
  {
    slug: "dripping-springs",
    name: "Dripping Springs",
    metroSlug: "austin-metro",
    metroName: "Austin Metro",
    metaTitle: "House Cleaning in Dripping Springs, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides event-cleanup and Airbnb cleaning in Dripping Springs, TX. Ranch and venue turnover specialists. Licensed and insured. Free quote today.",
    intro: "Dripping Springs has earned its reputation as the wedding capital of Texas — a Hill Country gem where vineyard wedding venues, ranch event spaces, and luxury vacation rentals have created a booming hospitality economy alongside its longtime residential community. Cleaning in Dripping Springs means understanding both worlds: the post-event turnover that needs to happen fast after a 300-person wedding reception, and the ranch Airbnb that needs to be reset to 5-star standard before the next guests arrive Friday morning. TQ Cleaners is one of the few cleaning services in the Austin metro with real experience across both use cases — event-space cleanup, Airbnb turnovers, and the premium residential service that full-time Dripping Springs residents deserve. We're available same-week for new clients and offer flexible scheduling around peak event and STR seasons.",
    reasons: [
      { title: "Event-Cleanup Experts", body: "Post-wedding and post-event cleanup for Dripping Springs venues and private properties — fast, thorough, and staged for the next event." },
      { title: "Ranch-Airbnb Turnovers", body: "Hill Country vacation properties require specialized STR turnovers. We handle the scope, the linens, and the photo reports." },
      { title: "Same-Week Availability", body: "Event schedules don't wait. New Dripping Springs clients can typically be scheduled within the same week of inquiry." },
    ],
    faqs: [
      { q: "Do you handle post-event cleanup for wedding venues in Dripping Springs?", a: "Yes — we work with private property owners in the Dripping Springs area for post-event cleanup. This is typically quoted per-event based on scope and guest count." },
      { q: "Can you handle STR turnovers for Hill Country ranch properties in Dripping Springs?", a: "Yes — ranch-style vacation rentals with multiple structures, outdoor areas, and unique layouts are part of our STR service in this area. We quote per-property based on specific scope." },
    ],
    neighbors: ["bee-cave", "lakeway", "buda", "austin"],
  },
  // ─── DALLAS METRO ───
  {
    slug: "dallas",
    name: "Dallas",
    metroSlug: "dallas-metro",
    metroName: "Dallas Metro",
    metaTitle: "House Cleaning in Dallas, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides professional house and commercial cleaning in Dallas, TX. Corporate condo experts, recurring service, same-day quotes. Licensed and insured.",
    intro: "Dallas is the hub of North Texas's sprawling metro — a city of dramatic contrasts, from the gleaming towers of Uptown and the Arts District to the historic bungalows of Oak Cliff and the luxury estates of Preston Hollow. Cleaning in Dallas means understanding those contrasts: high-rise condo turnovers in the central districts, large-home maintenance in the Park Cities and Preston Hollow corridors, and the professional-grade commercial cleaning that the city's corporate infrastructure demands. TQ Cleaners serves Dallas homeowners, condo owners, and businesses with the same flat-rate, licensed, insured service we deliver across Central and North Texas. Same-day quotes are available for all Dallas properties, and our recurring service keeps Dallas's busy professional households consistently clean without the management overhead of coordinating a freelance cleaner.",
    reasons: [
      { title: "Corporate-Condo Experts", body: "Dallas's Uptown, Knox-Henderson, and Victory Park neighborhoods are condo-dense. We specialize in efficient condo cleaning that meets HOA standards." },
      { title: "Professional Recurring Service", body: "Dallas professionals need consistent cleaning without the management burden. We handle scheduling, reminders, and quality — you handle everything else." },
      { title: "Same-Day Quotes", body: "The Dallas market moves fast. We quote the same day you reach out — flat-rate, no ambiguity, ready to schedule immediately." },
    ],
    faqs: [
      { q: "Do you service the Uptown and Knox-Henderson areas of Dallas?", a: "Yes — Uptown, Knox-Henderson, Oak Lawn, Victory Park, and the surrounding central Dallas neighborhoods are well within our service area." },
      { q: "Can you provide commercial cleaning for Dallas office spaces with a COI?", a: "Yes — full commercial liability insurance and COI documentation available within 24 hours for Dallas business clients." },
    ],
    neighbors: ["plano", "frisco", "richardson", "fort-worth"],
  },
  {
    slug: "plano",
    name: "Plano",
    metroSlug: "dallas-metro",
    metroName: "Dallas Metro",
    metaTitle: "House Cleaning in Plano, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides relocation move-in cleaning and recurring house cleaning in Plano, TX. Large-home crews, reliable weekly service. Licensed and insured. Free quote.",
    intro: "Plano is one of the most significant corporate-relocation destinations in the entire United States — home to the North American headquarters of Toyota, JPMorgan Chase, Liberty Mutual, and dozens of other major corporations that have transplanted thousands of employees from across the country into the Plano suburbs. Every relocation means a family arriving from California, New York, Illinois, or overseas who needs a move-in clean before they can truly settle into their new home. TQ Cleaners is Plano's go-to relocation cleaning service: detailed move-in cleans coordinated with realtors and property managers, same-week availability for last-minute arrivals, and seamless transition into recurring service once the family is settled. Plano's homes also tend toward the larger end of the spectrum — we staff appropriately for the square footage so nothing is rushed.",
    reasons: [
      { title: "Relocation Move-In Cleans", body: "Plano's corporate relocation market is one of the most active in Texas. We specialize in coordinating move-in cleans with realtors for out-of-state arrivals." },
      { title: "Large-Home Crews", body: "Plano homes run large. Multi-person crews handle the square footage efficiently without cutting corners." },
      { title: "Reliable Weekly Service", body: "Once settled, Plano families count on consistent recurring cleaning. Same team, same day, same result every visit." },
    ],
    faqs: [
      { q: "We're relocating to Plano from out of state — can you coordinate a move-in clean?", a: "Yes — this is one of our most common requests in Plano. We coordinate with your realtor or property manager, access the home before your furniture arrives, and send photo confirmation when done." },
      { q: "Do you offer recurring cleaning for larger Plano homes in the 4,000+ sq ft range?", a: "Yes — larger homes are common in Plano and we staff multi-person crews for efficient, thorough service. Flat-rate pricing covers the full scope." },
    ],
    neighbors: ["dallas", "frisco", "richardson", "fort-worth"],
  },
  {
    slug: "frisco",
    name: "Frisco",
    metroSlug: "dallas-metro",
    metroName: "Dallas Metro",
    metaTitle: "House Cleaning in Frisco, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers post-build and luxury house cleaning in Frisco, TX. Multi-gen household expertise, weekly maintenance plans. Licensed and insured. Free quote today.",
    intro: "Frisco is a phenomenon — consistently ranked among the fastest-growing cities in the United States, a master-planned community that has transformed from North Dallas farmland into a thriving city of 200,000+ in less than two decades. New construction is constant in Frisco, and the city's explosive growth has brought not just young families but multi-generational households, corporate relocations, and luxury home buyers who expect a premium level of service. TQ Cleaners handles the full spectrum of Frisco's cleaning demands: post-construction cleans for new builds fresh off the assembly line, weekly luxury maintenance for Frisco's estate-scale properties, and the specialized care that multi-generational households — where three generations share a home and everyone has different needs — require from a cleaning service.",
    reasons: [
      { title: "Post-Build Cleans", body: "Frisco's construction boom means constant demand for post-build cleanup. We get new homes move-in ready from builder-grade mess." },
      { title: "Multi-Gen Household Expertise", body: "Multi-generational homes have unique cleaning needs across age groups and sensitivities. We accommodate all of them." },
      { title: "Luxury Weekly Maintenance", body: "Frisco's larger luxury homes deserve premium weekly service. Same team, thorough checklist, consistent result every visit." },
    ],
    faqs: [
      { q: "Do you service the newer Frisco developments like Lexington, Shaddock Park, and Newman Village?", a: "Yes — we service throughout Frisco including the newest subdivisions. New construction in these communities is one of our primary Frisco service categories." },
      { q: "Can you accommodate multi-generational households with elderly residents in Frisco?", a: "Yes — multi-generational homes are a growing part of our Frisco client base. We offer fragrance-free, low-allergen products and can accommodate the specific needs of elderly household members." },
    ],
    neighbors: ["dallas", "plano", "richardson", "fort-worth"],
  },
  {
    slug: "richardson",
    name: "Richardson",
    metroSlug: "dallas-metro",
    metroName: "Dallas Metro",
    metaTitle: "House Cleaning in Richardson, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers house cleaning in Richardson, TX. Multi-cultural-home respect, tech-commute-friendly scheduling, pet-safe products. Licensed and insured. Free quote.",
    intro: "Richardson is one of Dallas's most diverse and dynamic communities — home to the Telecom Corridor, the University of Texas at Dallas, and a residential population that spans cultures, generations, and lifestyles in a way few Texas suburbs can match. The Telecom Corridor's legacy of tech employment and UTD's international academic community have made Richardson a truly multicultural city where residents come from across the country and around the world. TQ Cleaners approaches every Richardson home with genuine cultural respect — we don't assume one cleaning standard fits all, we communicate clearly, and we accommodate specific requests and preferences that reflect the diverse households we serve. Tech-commuter-friendly scheduling accounts for the long hours that Richardson's tech workforce keeps, and our pet-safe products protect the animals that share Richardson homes.",
    reasons: [
      { title: "Multi-Cultural Home Respect", body: "Richardson's diverse community means diverse household needs. We communicate clearly, accommodate preferences, and clean with respect for every home's character." },
      { title: "Tech-Commute-Friendly Scheduling", body: "Late starts, remote-work windows, and flexible time blocks accommodate Richardson's tech and academic workforce schedules." },
      { title: "Pet-Safe Products", body: "Non-toxic, pet-safe products throughout. Safe for the dogs, cats, and other animals that share Richardson households." },
    ],
    faqs: [
      { q: "Do you clean near the UTD campus and the Telecom Corridor in Richardson?", a: "Yes — these are among our primary Richardson service areas. We clean student housing, faculty homes, and the professional residences throughout the Telecom Corridor neighborhoods." },
      { q: "Can you accommodate specific product preferences or cultural household considerations in Richardson?", a: "Absolutely. We welcome specific product requests and household instructions. If you have preferences about which areas receive priority, how specific items are handled, or which products are used where, just let us know when booking." },
    ],
    neighbors: ["dallas", "plano", "frisco", "fort-worth"],
  },
  // ─── FORT WORTH METRO ───
  {
    slug: "fort-worth",
    name: "Fort Worth",
    metroSlug: "fort-worth-metro",
    metroName: "Fort Worth Metro",
    metaTitle: "House Cleaning in Fort Worth, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides trusted house cleaning in Fort Worth, TX. Local-owner accountability, historic-home care, fair flat-rate pricing. Licensed and insured. Free quote.",
    intro: "Fort Worth is Cowtown — a city that wears its Western heritage proudly from the Stockyards to Sundance Square while simultaneously growing into one of Texas's most dynamic metros. Fort Worth's residential landscape is as varied as its character: Victorian homes in the Fairmount historic district, modern condos in the Near Southside, established neighborhoods in the Cultural District, and rapidly growing suburban communities in the far west. TQ Cleaners serves Fort Worth homeowners and businesses with the same values that define the city itself — local ownership, straight dealing, and fair prices for honest work. We're not a franchise. We're a Texas-owned business that treats your home with the same pride that Fort Worth residents bring to their community.",
    reasons: [
      { title: "Local-Owner Accountability", body: "Owner-operated by Luis — not a franchise. Fort Worth residents get real accountability and direct communication, not a call center." },
      { title: "Historic-Home Care", body: "Fort Worth's Fairmount, Ryan Place, and Berkeley neighborhoods feature older homes that require surface-specific, careful cleaning." },
      { title: "Fair Flat-Rate Pricing", body: "Transparent pricing with no hidden fees, no hourly ambiguity, and no upsells at the door. What we quote is what you pay." },
    ],
    faqs: [
      { q: "Do you clean in Fort Worth's historic Fairmount and Ryan Place neighborhoods?", a: "Yes — we regularly clean homes in Fairmount, Ryan Place, Berkeley, and other historic Fort Worth neighborhoods. We're experienced with the older finishes, hardwood floors, and plaster walls common in these communities." },
      { q: "Do you offer commercial cleaning for Fort Worth businesses?", a: "Yes — office and commercial cleaning is available throughout Fort Worth. Full COI, flexible after-hours scheduling, and month-to-month contracts with no lock-in." },
    ],
    neighbors: ["arlington", "grapevine", "southlake", "dallas"],
  },
  {
    slug: "arlington",
    name: "Arlington",
    metroSlug: "fort-worth-metro",
    metroName: "Fort Worth Metro",
    metaTitle: "House Cleaning in Arlington, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners offers house cleaning in Arlington, TX. Event-cleanup service, large-home crews, weekend availability for game days. Licensed and insured. Free quote.",
    intro: "Arlington sits in the geographic heart of the DFW Metroplex — the city between Dallas and Fort Worth that is home to AT&T Stadium, Globe Life Field, and Six Flags over Texas. Arlington's identity is shaped by its entertainment venues, its diverse residential communities, and the constant flow of events that bring hundreds of thousands of visitors to the city each year. For Arlington homeowners, that means cleaning needs that sometimes don't fit a standard schedule: post-game-day house cleanups after home entertainment, event-adjacent property preparation, and the large-home service that Arlington's established suburbs require. TQ Cleaners handles it all — from the large families in the Dalworthington Gardens area to the rental properties near the Sports District that see heavy turnover around game days.",
    reasons: [
      { title: "Event-Cleanup Service", body: "Game days and events generate real cleaning needs. We schedule post-event cleanups for Arlington homeowners who entertain around the Sports District calendar." },
      { title: "Large-Home Crews", body: "Arlington's established neighborhoods feature homes with significant square footage. We staff multi-person crews for efficient, thorough results." },
      { title: "Weekend Availability", body: "Game days are weekends. Events are weekends. We staff Saturday and Sunday service in Arlington without a weekend premium." },
    ],
    faqs: [
      { q: "Can you do post-game-day cleanup for Arlington residents who host large gatherings?", a: "Yes — post-event and post-gathering cleanup is a popular service in Arlington given the city's sports and entertainment calendar. Quote is based on scope and guest count." },
      { q: "Do you clean rental properties near the Sports District in Arlington?", a: "Yes — investment and rental properties in the Sports District area are well within our service area. We offer STR turnovers and move-in/move-out cleans for these properties." },
    ],
    neighbors: ["fort-worth", "grapevine", "southlake", "dallas"],
  },
  {
    slug: "grapevine",
    name: "Grapevine",
    metroSlug: "fort-worth-metro",
    metroName: "Fort Worth Metro",
    metaTitle: "House Cleaning in Grapevine, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides Airbnb and STR cleaning in Grapevine, TX near DFW Airport. Same-day turnovers, host-friendly communication. Licensed and insured. Free quote.",
    intro: "Grapevine is one of the DFW Metroplex's most uniquely positioned cities — a historic Main Street community directly adjacent to DFW International Airport, making it one of the most active short-term rental markets in North Texas. Business travelers, airline crews, and leisure visitors fill Grapevine's STR properties year-round, and the fast check-out/check-in windows that the travel market demands are a constant pressure on hosts. TQ Cleaners has built specialized capacity for the Grapevine STR market: efficient same-day turnovers, hotel-quality bed staging, damage photo reporting, and the host-friendly communication that keeps your listing running smoothly. Beyond the STR market, Grapevine's established residential community and the beautiful historic district offer a quieter side of the city where recurring residential cleaning clients trust TQ Cleaners for consistent, professional service.",
    reasons: [
      { title: "DFW-Airbnb Turnover Specialists", body: "Same-day turnovers built for the DFW travel market. We fill the 11 AM → 3 PM window so you never have to push a check-in." },
      { title: "Same-Day Turnarounds", body: "Our Grapevine STR team maintains capacity for back-to-back same-day turnovers through peak travel periods." },
      { title: "Host-Friendly Communication", body: "Photo walkthrough after every clean. Damage, missing items, and low supplies reported immediately — before your next guest arrives." },
    ],
    faqs: [
      { q: "How much notice do you need for an STR turnover in Grapevine?", a: "For scheduled turnovers, 24–48 hours is preferred. For last-minute needs, call us directly — we maintain same-day capacity for established Grapevine STR clients." },
      { q: "Do you service Grapevine's historic Main Street area for residential cleaning?", a: "Yes — we clean throughout Grapevine's residential areas including the historic district. Older homes near Main Street may have heritage surfaces we'll treat appropriately." },
    ],
    neighbors: ["fort-worth", "arlington", "southlake", "dallas"],
  },
  {
    slug: "southlake",
    name: "Southlake",
    metroSlug: "fort-worth-metro",
    metroName: "Fort Worth Metro",
    metaTitle: "House Cleaning in Southlake, TX | TQ Cleaners",
    metaDesc: "TQ Cleaners provides luxury estate cleaning in Southlake, TX. Vetted-team discretion, concierge scheduling, premium detail. Licensed and insured. Free quote today.",
    intro: "Southlake is consistently ranked among the wealthiest cities in Texas — a community of executive estates, premium developments, and a residential standard that reflects the success of the corporate and professional families who live here. Carroll ISD's reputation and Southlake Town Square's amenities have made this one of the most sought-after addresses in the entire DFW Metroplex. Cleaning at the Southlake level requires more than showing up with supplies — it requires teams that have been rigorously vetted, trained specifically for luxury finishes and high-value surfaces, and held to an accountability standard that matches the community's expectations. TQ Cleaners built our luxury estate service precisely for communities like Southlake: concierge scheduling, detailed pre-visit briefings, consistent team assignment, and zero tolerance for anything less than perfect.",
    reasons: [
      { title: "Luxury-Home Expertise", body: "Custom finishes, premium appliances, high-end surfaces — we use the right products and techniques for every material in Southlake's estates." },
      { title: "Vetted-Team Discretion", body: "Background-checked, reference-verified teams with strict confidentiality. The same trusted professionals every visit." },
      { title: "Concierge Scheduling", body: "Proactive confirmation, arrival notifications, completion summaries, and immediate escalation if anything is less than perfect." },
    ],
    faqs: [
      { q: "How do you select and vet teams for Southlake estate properties?", a: "Southlake clients receive our most rigorously vetted team members — background check, reference verification, and supervised in-home evaluation before independent assignment. Team members assigned to Southlake properties are our most experienced and trusted." },
      { q: "Can you service lakefront or golf-community properties in Southlake?", a: "Yes — Southlake's Timarron and Vaquero-area properties, as well as lakefront estates along Dove Lake, are within our service area. Large-property and multi-structure quoting is available." },
    ],
    neighbors: ["fort-worth", "arlington", "grapevine", "plano"],
  },
];
