export interface ServiceData {
  slug: string;
  name: string;
  shortDesc: string;
  icon: string;
  metaTitle: string;
  metaDesc: string;
  heroTitle: string;
  overview: string[];
  included: string[];
  benefits: { title: string; body: string }[];
  faqs: { q: string; a: string }[];
}

export const SERVICES_DATA: ServiceData[] = [
  {
    slug: "standard-house-cleaning",
    name: "Standard House Cleaning",
    shortDesc: "Recurring weekly, bi-weekly, or monthly cleaning for busy households.",
    icon: "Home",
    metaTitle: "Standard House Cleaning | TQ Cleaners — San Antonio, Austin, Dallas & Fort Worth",
    metaDesc: "TQ Cleaners provides reliable standard house cleaning — weekly, bi-weekly, or monthly — across San Antonio, Austin, Dallas, and Fort Worth. Same team, flat-rate pricing.",
    heroTitle: "Standard House Cleaning in San Antonio, Austin, Dallas & Fort Worth",
    overview: [
      "Recurring house cleaning is the easiest investment you can make in your home and your sanity. TQ Cleaners offers weekly, bi-weekly, and monthly cleaning plans for busy households across Central and North Texas — giving you a consistently tidy space without sacrificing your weekends.",
      "Every standard clean covers the most-used areas of your home: kitchens, bathrooms, living areas, and bedrooms. Our background-checked, insured team arrives on schedule, brings all eco-friendly supplies, and executes the same thorough process every single visit so you never come home to a missed spot.",
      "Whether you have a small apartment in Austin, a busy family home in San Antonio, or a high-traffic household in Frisco or Fort Worth, we build your cleaning plan around your home's unique needs and schedule. Flat-rate pricing means no hourly surprises — you know exactly what you're paying before we show up.",
      "Most clients start with a deep clean to reset their home, then move to a standard recurring plan. If this is your first visit, ask about bundling — we frequently offer first-visit discounts for new recurring customers.",
    ],
    included: [
      "Dusting all surfaces, shelves, and décor",
      "Vacuuming all carpets and rugs",
      "Mopping all hard-floor surfaces",
      "Kitchen counter wipe-down, stovetop, appliance exteriors, sink",
      "Bathroom scrub: toilet, shower, tub, sink, mirror, floor",
      "Bedroom tidy and surface dusting",
      "Trash removal throughout home",
      "Light organization of visible surfaces",
      "Window sills dusted",
      "Spot-clean baseboards",
      "Microwave interior wipe-down",
      "Light switch and door handle wipe-down",
    ],
    benefits: [
      { title: "Consistent Results Every Visit", body: "Same checklist, same team, same standards — your home looks the same level of spotless every time we leave." },
      { title: "More Time for What Matters", body: "Reclaim your weekends and evenings. Stop spending Saturday mornings scrubbing and start enjoying your home." },
      { title: "Same Trusted Team Every Time", body: "We assign a dedicated crew to your home so they know your preferences, your pets, and your space." },
    ],
    faqs: [
      { q: "How often should I book a standard cleaning?", a: "Most clients book bi-weekly — frequent enough to stay consistently clean without the premium of weekly service. Families with kids or pets often prefer weekly. Solo professionals or low-traffic spaces may find monthly sufficient. We'll recommend the right frequency after a quick conversation about your home." },
      { q: "Do I need to be home during the cleaning?", a: "No — most of our clients are not home. We're fully background-checked and insured. You'll receive arrival and completion notifications so you always know when our team is there and when they've finished. Many clients leave a lockbox code or trusted access method." },
      { q: "Do you bring your own cleaning supplies?", a: "Yes, we bring all supplies for every visit — all eco-friendly, plant-based products safe for kids and pets. If you have a favorite product you'd like us to use or a sensitivity to a certain ingredient, just let us know and we'll accommodate." },
    ],
  },
  {
    slug: "deep-cleaning",
    name: "Deep Cleaning",
    shortDesc: "Top-to-bottom 50-point reset — inside appliances, baseboards, vents, and more.",
    icon: "Sparkles",
    metaTitle: "Deep Cleaning Services | TQ Cleaners — San Antonio, Austin, Dallas & Fort Worth",
    metaDesc: "TQ Cleaners deep cleaning tackles inside appliances, grout, vents, baseboards, and more across San Antonio, Austin, Dallas, and Fort Worth. 50-point checklist. Get a free quote today.",
    heroTitle: "Deep Cleaning Services in San Antonio, Austin, Dallas & Fort Worth",
    overview: [
      "A deep clean is the reset your home needs — not just surface-level tidying, but a top-to-bottom tackle of every area that accumulates grime over months or years: inside appliances, grout lines, ceiling fans, door frames, vents, blinds, and behind furniture. TQ Cleaners brings a 50-point deep cleaning checklist to every job across Texas.",
      "Deep cleaning is ideal for first-time customers (we almost always recommend starting here), seasonal resets (spring and fall are most popular), pre-event preparation, post-construction cleanup, or any home that hasn't had a thorough cleaning in six months or more.",
      "Our trained, insured team works systematically through your home with the right tools and eco-friendly cleaning agents for each surface. We don't cut corners — if it's on the checklist, it gets done. You'll notice the difference in areas that standard cleaning rarely reaches.",
      "After a deep clean, transitioning to a recurring standard plan keeps your home at that same level of clean without the premium of repeated deep cleans. Most clients find quarterly deep cleans combined with bi-weekly standard service to be the optimal combination.",
    ],
    included: [
      "Everything in a standard clean, plus:",
      "Inside oven (includes racks and door glass)",
      "Inside refrigerator (on request)",
      "Inside microwave (full scrub)",
      "Hand-wiped baseboards throughout",
      "Door frames and door tops",
      "Ceiling fans and light fixtures",
      "Air vents and registers",
      "Blinds (wiped or vacuumed)",
      "Interior window cleaning",
      "Grout scrubbing (tile floors and showers)",
      "Behind and under all movable furniture",
      "Cabinet fronts and knobs",
      "Drawer interiors (on request)",
    ],
    benefits: [
      { title: "Deep Sanitization", body: "Removes allergens, bacteria, and grease in areas standard cleaning doesn't reach — including AC vents, grout, and inside appliances." },
      { title: "Tackles Year-of-Buildup Areas", body: "Grease behind the stove, dust on ceiling fan blades, hard-water deposits in showers — gone. Your home feels genuinely renewed." },
      { title: "50-Point Detailed Checklist", body: "Every area is accounted for on a written checklist reviewed by your team lead. You can see exactly what was cleaned when we're done." },
    ],
    faqs: [
      { q: "How long does a deep clean take?", a: "A standard 3-bedroom deep clean typically takes 4–6 hours with a 2-person team. Larger homes or heavily soiled spaces may take longer. We provide an exact time window at quoting so you can plan your day. We never rush and don't leave until the checklist is complete." },
      { q: "How often should I schedule a deep clean?", a: "Most Texas homeowners benefit from twice-per-year deep cleans — spring (March/April after cedar season) and fall (September/October after summer). First-time customers almost always start with a deep clean to establish a baseline, then move to a recurring standard plan." },
      { q: "Is a deep clean worth the extra cost over a standard clean?", a: "Absolutely. A deep clean removes the buildup that causes allergens, odors, and premature wear on surfaces. It resets your home so recurring standard cleans stay effective — without a deep clean baseline, standard cleaning is just maintaining a layer of hidden grime. Most clients who experience a TQ deep clean become recurring clients within the month." },
    ],
  },
  {
    slug: "move-in-move-out",
    name: "Move-In / Move-Out Cleaning",
    shortDesc: "Complete turnover cleans with deposit-back guarantee for tenants and landlords.",
    icon: "Truck",
    metaTitle: "Move-In / Move-Out Cleaning | TQ Cleaners — San Antonio, Austin, Dallas & Fort Worth",
    metaDesc: "TQ Cleaners move-in/move-out cleaning with a deposit-back guarantee. Complete turnover cleans for tenants, landlords, and property managers across Texas. Same-day availability.",
    heroTitle: "Move-In / Move-Out Cleaning in San Antonio, Austin, Dallas & Fort Worth",
    overview: [
      "Moving is stressful. The cleaning doesn't have to be. TQ Cleaners handles complete move-out and move-in cleaning for tenants, homeowners, landlords, and property managers across San Antonio, Austin, Dallas, and Fort Worth — so you can focus on the move itself.",
      "Our move-out cleans are deep-level turnovers that treat the property as if no one ever lived there. Inside every cabinet, every appliance, every closet, every baseboard — every inch that a landlord or property manager will inspect before returning your deposit or preparing for new occupants.",
      "Move-in cleans give new residents the fresh start they deserve. Whether you're moving into a home that feels clean or one that clearly wasn't professionally cleaned, we bring it to TQ Cleaners standard before you unpack a single box.",
      "Property managers across all four Texas metros rely on TQ Cleaners for multi-unit turnovers, same-week scheduling, and professional COI documentation. We have the team capacity and scheduling flexibility to handle portfolios of any size.",
    ],
    included: [
      "Inside all cabinets and drawers",
      "Inside all appliances: oven, refrigerator, microwave, dishwasher",
      "Inside all closets (shelves, floors, corners)",
      "All baseboards (hand-wiped)",
      "All door frames and door surfaces",
      "All blinds (wiped or vacuumed)",
      "All interior windows and sills",
      "All air vents and registers",
      "Light fixtures and ceiling fans",
      "Grout scrubbing (kitchen and bathrooms)",
      "Detailed kitchen and bathroom scrub",
      "All floors (vacuum + mop)",
      "Wall scuff spot-cleaning",
      "Garage sweep (if applicable)",
    ],
    benefits: [
      { title: "Deposit-Back Guarantee", body: "We clean to inspection standard. If the landlord cites a cleaning issue, we return within 48 hours at no charge to make it right." },
      { title: "Property-Manager Approved", body: "Trusted by PMs across all four Texas metros for multi-unit turnovers, professional documentation, and flexible scheduling." },
      { title: "Ready-for-New-Tenants Finish", body: "Move-out cleans meet the standard that makes new tenants feel confident in their new home from day one." },
    ],
    faqs: [
      { q: "Do you guarantee deposit return?", a: "We guarantee the property will pass a standard move-out inspection for cleaning. If the landlord or property manager cites a specific cleaning issue after our clean, we return within 48 hours to address it at no additional charge. The deposit-back guarantee applies to cleaning-related deductions — we can't control wear and tear or damage, but cleaning will never be the reason you lose part of your deposit." },
      { q: "Do you offer bulk pricing for property managers?", a: "Yes — we serve property managers across all four Texas metros with multi-unit contract pricing. We can handle simultaneous turnovers for multi-unit properties with flexible scheduling and professional documentation including COI. Contact us for a portfolio quote." },
      { q: "Can you do same-day or next-day move-out cleans?", a: "In most cases yes with 24–48 hours' notice, depending on team availability and property size. We prioritize scheduling flexibility for move-out situations since timelines are often tight. Call us directly at (956) 306-6378 for urgent turnarounds." },
    ],
  },
  {
    slug: "short-term-rental-airbnb",
    name: "Short-Term Rental / Airbnb Cleaning",
    shortDesc: "Hotel-quality resets between guests — linens, restock, and damage reports included.",
    icon: "Star",
    metaTitle: "Airbnb & Short-Term Rental Cleaning | TQ Cleaners — Texas",
    metaDesc: "TQ Cleaners provides hotel-quality Airbnb and VRBO cleaning across San Antonio, Austin, Dallas, and Fort Worth. Same-day turnovers, linen handling, and damage photo reports.",
    heroTitle: "Short-Term Rental & Airbnb Cleaning in San Antonio, Austin, Dallas & Fort Worth",
    overview: [
      "Cleanliness is the #1 factor in Airbnb guest reviews — and a single 3-star rating for cleaning can tank your listing's visibility for months. TQ Cleaners provides hotel-quality turnover cleaning for Airbnb, VRBO, and short-term rental hosts across Texas, so your guests always walk into a property that exceeds expectations.",
      "Our STR-specialized team handles everything between check-out and check-in: full room resets, hotel-style bed-making, towel staging, bathroom restocking, kitchen reset, dishwasher cycle, trash removal, inventory check, damage/missing-item photo reporting, and a final walkthrough staging for photos.",
      "We specialize in the tight 11 AM → 3 PM check-out/check-in windows that define STR hosting. Our scheduling system tracks your booking calendar and confirms turnovers in advance — so you never have to scramble last-minute or risk a late check-in.",
      "STR hosts in Austin, New Braunfels, Grapevine, Dallas, and Fort Worth rely on TQ Cleaners as their turnover partner — some for single properties, others for portfolios of 12+ units. We grow with your hosting business.",
    ],
    included: [
      "Full reset of every room",
      "Hotel-style bed-making with fresh linens",
      "Towel replacement, folding, and staging",
      "Bathroom restock (toiletries, paper goods)",
      "Full kitchen reset (counters, appliances, sink)",
      "Dishwasher run or hand-wash of dishes",
      "Trash and recycling removal",
      "Inventory check (supplies, amenities)",
      "Damage and missing-item photo reporting",
      "Property staging for listing photos",
      "Final walkthrough and quality sign-off",
    ],
    benefits: [
      { title: "Hotel-Quality Reset", body: "Guests walk in and immediately feel the 5-star difference — crisp beds, spotless bathrooms, staged surfaces ready for photos." },
      { title: "Same-Day Turnarounds", body: "Our STR team specializes in tight check-out/check-in windows. We work the 11 AM → 3 PM turnaround so you never have to push a check-in." },
      { title: "Host-Friendly Communication", body: "Every clean ends with a photo walkthrough by text — damage, missing items, and low supplies reported immediately so you're never blindsided." },
    ],
    faqs: [
      { q: "Can you handle same-day checkout-to-check-in windows?", a: "Yes — our STR-specialized team is built for same-day turnarounds. We work the standard 11 AM check-out to 3 PM check-in window. For back-to-back bookings, book us as soon as the reservation is confirmed so we can guarantee the slot. We track your calendar and confirm each turnover 24 hours in advance." },
      { q: "Do you handle laundry?", a: "We offer two linen options: on-site wash-and-return (we wash and dry on-site in your unit's machines, add time to turnaround) or off-site swap service where we swap out used linens for a clean set from your pre-washed inventory or ours. Pricing is based on linen inventory size. Both options ensure guests always get fresh linens." },
      { q: "How do damage reports work?", a: "Every clean ends with a structured photo walkthrough of every room. Any damage, missing items, or low supplies are photographed and sent to you by text within minutes of the clean completing. You have documentation before your next guest checks in — critical for Airbnb host-protection claims and resolution center disputes." },
    ],
  },
  {
    slug: "office-commercial",
    name: "Office & Commercial Cleaning",
    shortDesc: "Flexible after-hours commercial cleaning with full COI available in 24 hours.",
    icon: "Building2",
    metaTitle: "Office & Commercial Cleaning | TQ Cleaners — San Antonio, Austin, Dallas & Fort Worth",
    metaDesc: "TQ Cleaners provides professional office and commercial cleaning across Texas — after-hours, full COI, month-to-month contracts. Serving businesses in San Antonio, Austin, Dallas, and Fort Worth.",
    heroTitle: "Office & Commercial Cleaning in San Antonio, Austin, Dallas & Fort Worth",
    overview: [
      "A clean workplace isn't a luxury — it's a business necessity. TQ Cleaners provides professional commercial cleaning for offices, medical practices, retail spaces, and commercial buildings across San Antonio, Austin, Dallas, and Fort Worth. We work around your business hours so operations are never disrupted.",
      "Every commercial client receives full liability insurance documentation and a COI naming your building or property manager as additional insured, typically available within 24 hours of agreement. We're already trusted by property managers and building owners across Texas for exactly this reason.",
      "Our commercial cleaning programs are flexible by design: after-hours cleaning, early-morning service, weekend-only schedules, and hybrid plans that match your occupancy patterns. Month-to-month contracts with no lock-in mean you can scale service up or down as your business evolves.",
      "From a 10-person startup office in Austin to a 20,000 sq ft corporate headquarters in Plano, TQ Cleaners scales to match your facility — with consistent team assignment, detailed scope documentation, and a dedicated account contact for scheduling and changes.",
    ],
    included: [
      "Desk and workstation dusting and wipe-down",
      "Trash and recycling removal",
      "Kitchen and breakroom cleaning and sanitizing",
      "Restroom deep-clean and restocking",
      "Vacuuming all carpets and rugs",
      "Mopping all hard-floor surfaces",
      "Glass and entryway cleaning",
      "Conference room resets",
      "Lobby and reception area cleaning",
      "High-touch disinfection: handles, switches, elevator buttons",
      "Floor care (strip, wax, buff — by request)",
    ],
    benefits: [
      { title: "After-Hours Service", body: "We clean when your team is gone — early mornings, evenings, or weekends — so operations are never interrupted and your staff arrives to a fresh space." },
      { title: "Full Insurance + COI on File", body: "Full liability insurance with COI naming your property manager or building as additional insured, available within 24 hours of contract." },
      { title: "Flexible Month-to-Month Contracts", body: "No lock-in, no multi-year commitments. Scale frequency up or down as your business needs change — and cancel anytime with 30-day notice." },
    ],
    faqs: [
      { q: "Can you provide a certificate of insurance (COI)?", a: "Yes — we maintain full commercial liability insurance and can provide a COI naming your building owner or property manager as additional insured. In most cases we can have the certificate to you within 24 hours of signing an agreement. This is standard for all our commercial accounts and we've never had an issue fulfilling a building's insurance requirements." },
      { q: "Do you clean medical offices?", a: "Yes — our commercial team is trained on OSHA bloodborne-pathogen protocols and we use hospital-grade EPA-registered disinfectants appropriate for medical environments. We clean exam rooms, waiting areas, offices, and restrooms. We do not handle regulated medical waste disposal, but we work alongside your waste management protocols without disruption." },
      { q: "What is your minimum contract?", a: "We offer month-to-month contracts with no lock-in period. Many clients clean 3x or 5x per week; others start with once-weekly service and scale up. We also handle one-time post-construction cleans, event post-cleanup, and deep cleans with no ongoing commitment required. Call us to discuss the right frequency for your space." },
    ],
  },
  {
    slug: "custom-packages",
    name: "Custom Packages",
    shortDesc: "Fully tailored cleaning plans for unique homes, estates, and businesses.",
    icon: "Settings",
    metaTitle: "Custom Cleaning Packages | TQ Cleaners — San Antonio, Austin, Dallas & Fort Worth",
    metaDesc: "TQ Cleaners builds custom cleaning plans for oversized homes, estates, post-construction, post-event, luxury maintenance, and more across Texas. Flat-rate pricing, same trusted team.",
    heroTitle: "Custom Cleaning Packages in San Antonio, Austin, Dallas & Fort Worth",
    overview: [
      "Not every home or business fits a standard cleaning package — and TQ Cleaners doesn't force it. Custom packages let us build a cleaning plan around your exact space, schedule, and priorities rather than making you pay for services you don't need or skip services you do.",
      "Custom packages are perfect for oversized properties and estates, multi-generational households with unique needs, post-construction and post-renovation cleanup, post-event and party cleanup, luxury weekly maintenance programs, allergy-focused deep cleans, pre-listing real estate preparation, and multi-property portfolios.",
      "Every custom package starts with a 10-minute phone or virtual walk-through to define scope. We then build a written flat-rate quote — the same price every visit with no hourly ambiguity. You know the total before we show up.",
      "The same background-checked, insured TQ Cleaners team handles every custom visit. We don't subcontract or send random crews — your custom package is executed by people you've already vetted and trust.",
    ],
    included: [
      "Any combination of standard, deep, move-out, STR, and commercial tasks",
      "Flexible scheduling — any frequency, any day of the week",
      "Flat-rate pricing defined in advance",
      "Same dedicated team every visit",
      "Scope documentation reviewed before each visit",
      "On-request specialty tasks (estate management, luxury detailing)",
      "Multi-property coordination for portfolio owners",
      "10-minute consultation to define exact scope",
    ],
    benefits: [
      { title: "Fully Tailored Scope", body: "Built around your property's actual needs — not a template. Pay for what you need, skip what you don't." },
      { title: "Flat-Rate Pricing", body: "The same clear, agreed-upon price every visit. No hourly tracking, no surprise add-ons, no negotiating after the fact." },
      { title: "Same Trusted Team", body: "Your custom package is handled by the same vetted crew every time — consistency is the foundation of every TQ Cleaners relationship." },
    ],
    faqs: [
      { q: "What kinds of custom jobs does TQ Cleaners handle?", a: "Post-construction and renovation cleanup, post-party and event resets, estate and downsize cleans, luxury weekly maintenance programs, allergy-focused deep cleans, pre-listing real estate preparation, multi-property portfolio management, and oversized or uniquely configured properties. If you have a cleaning need that doesn't fit a standard package, call us — we'll build it." },
      { q: "Are custom packages more expensive than standard services?", a: "Not necessarily — and often less. Because we scope exactly what you need, you're not paying for a blanket deep clean when you only need specific areas addressed. The 10-minute consultation lets us build the most efficient package for your situation, which is frequently priced below a comparable off-the-shelf service." },
      { q: "How does the quoting process work?", a: "A 10-minute phone call or virtual walk-through (video call or photos) defines the scope. We send a flat-rate written quote by text or email the same day. Once you approve, we schedule — same rate, same scope, every visit. Changes to scope are discussed and re-quoted before the next visit, never applied as surprise charges after the fact." },
    ],
  },
];
